name: Dafny CLI

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install Dafny"
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: "4.4.0"

      - name: Compile and test
        run: (cd sumplete && make)

    # - name: Run tests
    # run: | # TODO: Add test
