name: Dafny CLI

on:
  push:
    paths:
      - "sumplete/sumplete.dfy"
      - "sumplete/randomNum.cs"
  pull_request:
    paths:
      - "sumplete/sumplete.dfy"
      - "sumplete/randomNum.cs"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "4.4.0.0"

      - name: Compile and test
        run: (cd sumplete && make)

    # - name: Run tests
    # run: | # TODO: Add test
