name: Dafny CLI

on:
  push:
    paths:
      - "sumplete/sumplete.dfy"
  pull_request:
    paths:
      - "sumplete/sumplete.dfy"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1

      - name: Verify Dafny file
        run: dafny /compile:0 sumplete/sumplete.dfy

    # - name: Run tests
    # run: | # TODO: Add test
